
#define MSGTR_WhilePlaying "while playing"
#define INFOTR_MEDIAINFO "Media Information"
#define INFOTR_NORMAL "General"
#define INFOTR_VIDEO "Video"
#define INFOTR_AUDIO "Audio"
#define INFOTR_NAME "Filename"
#define INFOTR_DEMUXER "Meuxer"
#define INFOTR_SIZE "Size"
#define INFOTR_LENG "Length"
#define INFOTR_FORMAT "Format"
#define INFOTR_BITRATE "Bitrate"
#define INFOTR_CODEC "Codec"
#define INFOTR_CLIPINFO "Clip info"
#define INFOTR_VIDEO_RESOLUTION "Resolution"
#define INFOTR_VIDEO_ASPECT "Aspect"
#define INFOTR_VIDEO_FPS "Fps"
#define INFOTR_AUDIO_RATE "Samplerate"
#define INFOTR_AUDIO_NCH "Channels"
#define INFOTR_SUB "Subtitles"
#define INFOTR_UNKNOWN "Unknown"
#define INFOTR_TRACK "Track"

// mplayer.c OSD

#define GB_MSGTR_OSDenabled "已启用"
#define GB_MSGTR_OSDdisabled "已停用"
#define GB_MSGTR_OSDAudio "音频: %s"
#define GB_MSGTR_OSDVideo "视频: %s"
#define GB_MSGTR_OSDChannel "频道: %s"
#define GB_MSGTR_OSDSubDelay "字幕延迟: %d 毫秒"
#define GB_MSGTR_OSDSpeed "速度: x %6.2f"
#define GB_MSGTR_OSDosd "OSD: %s"
#define GB_MSGTR_OSDChapter "章节: (%d) %s"

// property values
#define GB_MSGTR_WhilePlaying "播放时"
#define GB_MSGTR_Enabled "已启用"
#define GB_MSGTR_EnabledEdl "已启用 EDL"
#define GB_MSGTR_Disabled "已停用"
#define GB_MSGTR_HardFrameDrop "强丢帧"
#define GB_MSGTR_Unknown "未知"
#define GB_MSGTR_Bottom "底部"
#define GB_MSGTR_Center "中部"
#define GB_MSGTR_Top "顶部"

// osd bar names
#define GB_MSGTR_Volume "音量"
#define GB_MSGTR_Panscan "摇移"
#define GB_MSGTR_Gamma "伽玛值"
#define GB_MSGTR_Brightness "亮度"
#define GB_MSGTR_Contrast "对比度"
#define GB_MSGTR_Saturation "饱和度"
#define GB_MSGTR_Hue "色调"
#define GB_MSGTR_Balance "均衡"

// property state
#define GB_MSGTR_LoopStatus "循环方式: %s"
#define GB_MSGTR_LoopStatus1 "关闭"
#define GB_MSGTR_LoopStatus2 "始终"
#define GB_MSGTR_MuteStatus "静音: %s"
#define GB_MSGTR_AVDelayStatus "A-V 延迟: %s"
#define GB_MSGTR_OnTopStatus "总在最前: %s"
#define GB_MSGTR_RootwinStatus "根窗口: %s"
#define GB_MSGTR_BorderStatus "边框: %s"
#define GB_MSGTR_FramedroppingStatus "丢帧: %s"
#define GB_MSGTR_VSyncStatus "视频同步: %s"
#define GB_MSGTR_SubSelectStatus "字幕: %s"
#define GB_MSGTR_SubSourceStatus "字幕源: %s"
#define GB_MSGTR_SubPosStatus "字幕位置: %s/100"
#define GB_MSGTR_SubAlignStatus "字幕对齐: %s"
#define GB_MSGTR_SubDelayStatus "字幕延迟: %s"
#define GB_MSGTR_SubScale "字幕大小: %s"
#define GB_MSGTR_SubVisibleStatus "显示字幕: %s"
#define GB_MSGTR_SubForcedOnlyStatus "只用锁定的字幕: %s"


// mplayer.c OSD

#define BIG5_MSGTR_OSDenabled "已啟用"
#define BIG5_MSGTR_OSDdisabled "已停用"
#define BIG5_MSGTR_OSDAudio "音頻: %s"
#define BIG5_MSGTR_OSDVideo "視頻: %s"
#define BIG5_MSGTR_OSDChannel "頻道: %s"
#define BIG5_MSGTR_OSDSubDelay "字幕延遲: %d 毫秒"
#define BIG5_MSGTR_OSDSpeed "速度: x %6.2f"
#define BIG5_MSGTR_OSDosd "OSD: %s"
#define BIG5_MSGTR_OSDChapter "章節: (%d) %s"

// property values
#define BIG5_MSGTR_LoopStatus "循環方式: %s"
#define BIG5_MSGTR_LoopStatus1 "關閉"
#define BIG5_MSGTR_LoopStatus2 "始終"
#define BIG5_MSGTR_WhilePlaying "播放時"
#define BIG5_MSGTR_Enabled "已啟用"
#define BIG5_MSGTR_EnabledEdl "已啟用 EDL"
#define BIG5_MSGTR_Disabled "已停用"
#define BIG5_MSGTR_HardFrameDrop "强丢幀"
#define BIG5_MSGTR_Unknown "未知"
#define BIG5_MSGTR_Bottom "底部"
#define BIG5_MSGTR_Center "中部"
#define BIG5_MSGTR_Top "頂部"

// osd bar names
#define BIG5_MSGTR_Volume "音量"
#define BIG5_MSGTR_Panscan "摇移"
#define BIG5_MSGTR_Gamma "Gamma"
#define BIG5_MSGTR_Brightness "亮度"
#define BIG5_MSGTR_Contrast "對比度"
#define BIG5_MSGTR_Saturation "飽和度"
#define BIG5_MSGTR_Hue "色調"
#define BIG5_MSGTR_Balance "均衡"

// property state
#define BIG5_MSGTR_MuteStatus "靜音: %s"
#define BIG5_MSGTR_AVDelayStatus "A-V 延遲: %s"
#define BIG5_MSGTR_OnTopStatus "總在最前: %s"
#define BIG5_MSGTR_RootwinStatus "根窗口: %s"
#define BIG5_MSGTR_BorderStatus "邊框: %s"
#define BIG5_MSGTR_FramedroppingStatus "丢幀: %s"
#define BIG5_MSGTR_VSyncStatus "視頻同步: %s"
#define BIG5_MSGTR_SubSelectStatus "字幕: %s"
#define BIG5_MSGTR_SubSourceStatus "字幕源: %s"
#define BIG5_MSGTR_SubPosStatus "字幕位置: %s/100"
#define BIG5_MSGTR_SubAlignStatus "字幕對齊: %s"
#define BIG5_MSGTR_SubDelayStatus "字幕延遲: %s"
#define BIG5_MSGTR_SubScale "字幕大小: %s"
#define BIG5_MSGTR_SubVisibleStatus "顯示字幕: %s"
#define BIG5_MSGTR_SubForcedOnlyStatus "祇用鎖定的字幕: %s"
